---
- name: updating
  apt: update_cache=yes
- name: configure login
  template: src=templates/login.defs dest=/etc/login.defs mode=0644
- name: configure ssh
  template: src=templates/sshd_config dest=/etc/ssh/sshd_config mode=0644
- name: enable sshd service
  service: name=ssh enabled=yes
- name: install base packages
  apt: name={{item}} state=present
  with_items:
    - vim
    - git
    - curl
    - clang
    - gcc
    - libavahi-compat-libdnssd-dev
    - python-dev
    - python-pip
    - cron
    - make
    - g++
    - avahi-daemon
    - avahi-discover
    - libnss-mdns
    - virtualenv