---
- name: installing deps via apt
  apt: name={{item}} state=present
  with_items:
    - python-pil
    - python-pillow
- name: upgrade pip
  shell: pip install pip --upgrade
- name: fix pip
  template: src=templates/pip dest=/usr/bin/pip mode=0755
- name: installing modules
  pip: name={{item}} state=present
  with_items:
    - netifaces
    - psutil
    - python-wifi
    - ssd1306
- name: install module ssd1306
  pip: name=git+https://github.com/codelectron/ssd1306/
- name: create work dirs
  action: file path={{item}} state=directory
  with_items:
    - /srv/base_scripts
    - /srv/base_logs
- name: copy scripts
  template: src=templates/{{item}} dest=/srv/base_scripts/{{item}}
  with_items:
    - sys_info.py

